<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metadata>
    <map>
        <entry>
            <key>DISPLAYNAME</key>
            <value>Task_Ping_device.php</value>
        </entry>
        <entry>
            <key>DATE_MODIFICATION</key>
            <value>1629730800339</value>
        </entry>
        <entry>
            <key>REPOSITORY</key>
            <value>ETSI-MANO</value>
        </entry>
        <entry>
            <key>DATE_CREATION</key>
            <value>1629730800336</value>
        </entry>
        <entry>
            <key>TAG</key>
        </entry>
        <entry>
            <key>FILE_TYPE</key>
            <value>text</value>
        </entry>
        <entry>
            <key>TYPE</key>
            <value>UPLOAD</value>
        </entry>
        <entry>
            <key>COMMENT</key>
        </entry>
    </map>
</metadata>
