/**
 *     Copyright (C) 2019-2020 Ubiqube.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * SOL003 - VNF Lifecycle Management interface
 * SOL003 - VNF Lifecycle Management interface definition  IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to. In case of discrepancies the published ETSI Group Specification takes precedence.  In clause 4.3.2 of ETSI GS NFV-SOL 003 v2.4.1, an attribute-based filtering mechanism is defined. This mechanism is currently not included in the corresponding OpenAPI design for this GS version. Changes to the attribute-based filtering mechanism are being considered in v2.5.1 of this GS for inclusion in the corresponding future ETSI NFV OpenAPI design. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis&list_id=61&product=NFV&resolution=
 *
 * OpenAPI spec version: 1.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ubiqube.etsi.mano.vnfm.v261.model.nslcm;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ubiqube.etsi.mano.common.v261.model.ResourceHandle;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * This type provides information about added, deleted, modified and temporary
 * VNFCs.
 */
@Schema(description = "This type provides information about added, deleted, modified and temporary VNFCs.   ")

public class AffectedVnfc {
	@JsonProperty("id")
	private String id = null;

	@JsonProperty("vduId")
	private String vduId = null;

	/**
	 * Signals the type of change. Permitted values: * ADDED * REMOVED * MODIFIED *
	 * TEMPORARY For a temporary resource, an AffectedVnfc structure exists as long
	 * as the temporary resource exists.
	 */
	public enum ChangeTypeEnum {
		ADDED("ADDED"),

		REMOVED("REMOVED"),

		MODIFIED("MODIFIED"),

		TEMPORARY("TEMPORARY");

		private final String value;

		ChangeTypeEnum(final String value) {
			this.value = value;
		}

		@Override
		@JsonValue
		public String toString() {
			return String.valueOf(value);
		}

		@JsonCreator
		public static ChangeTypeEnum fromValue(final String text) {
			for (final ChangeTypeEnum b : ChangeTypeEnum.values()) {
				if (String.valueOf(b.value).equals(text)) {
					return b;
				}
			}
			return null;
		}
	}

	@JsonProperty("changeType")
	private ChangeTypeEnum changeType = null;

	@JsonProperty("computeResource")
	private ResourceHandle computeResource = null;

	@JsonProperty("metadata")
	private Map<String, String> metadata = null;

	@JsonProperty("affectedVnfcCpIds")
	private List<String> affectedVnfcCpIds = null;

	@JsonProperty("addedStorageResourceIds")
	private List<String> addedStorageResourceIds = null;

	@JsonProperty("removedStorageResourceIds")
	private List<String> removedStorageResourceIds = null;

	public AffectedVnfc id(final String id) {
		this.id = id;
		return this;
	}

	/**
	 * Identifier of the Vnfc instance, identifying the applicable
	 * \&quot;vnfcResourceInfo\&quot; entry in the \&quot;VnfInstance\&quot; data
	 * type.
	 *
	 * @return id
	 **/
	@JsonProperty("id")
	@Schema(required = true, description = "Identifier of the Vnfc instance, identifying the applicable \"vnfcResourceInfo\" entry in the \"VnfInstance\" data type. ")
	@NotNull
	public String getId() {
		return id;
	}

	public void setId(final String id) {
		this.id = id;
	}

	public AffectedVnfc vduId(final String vduId) {
		this.vduId = vduId;
		return this;
	}

	/**
	 * Identifier of the related VDU in the VNFD.
	 *
	 * @return vduId
	 **/
	@JsonProperty("vduId")
	@Schema(required = true, description = "Identifier of the related VDU in the VNFD. ")
	@NotNull
	public String getVduId() {
		return vduId;
	}

	public void setVduId(final String vduId) {
		this.vduId = vduId;
	}

	public AffectedVnfc changeType(final ChangeTypeEnum changeType) {
		this.changeType = changeType;
		return this;
	}

	/**
	 * Signals the type of change. Permitted values: * ADDED * REMOVED * MODIFIED *
	 * TEMPORARY For a temporary resource, an AffectedVnfc structure exists as long
	 * as the temporary resource exists.
	 *
	 * @return changeType
	 **/
	@JsonProperty("changeType")
	@Schema(required = true, description = "Signals the type of change. Permitted values: * ADDED * REMOVED * MODIFIED * TEMPORARY For a temporary resource, an AffectedVnfc structure exists as long as the temporary resource exists. ")
	@NotNull
	public ChangeTypeEnum getChangeType() {
		return changeType;
	}

	public void setChangeType(final ChangeTypeEnum changeType) {
		this.changeType = changeType;
	}

	public AffectedVnfc computeResource(final ResourceHandle computeResource) {
		this.computeResource = computeResource;
		return this;
	}

	/**
	 * Reference to the VirtualCompute resource. Detailed information is (for new
	 * and modified resources) or has been (for removed resources) available from
	 * the VIM.
	 *
	 * @return computeResource
	 **/
	@JsonProperty("computeResource")
	@Schema(required = true, description = "Reference to the VirtualCompute resource. Detailed information is (for new and modified resources) or has been (for removed resources) available from the VIM. ")
	@NotNull
	public ResourceHandle getComputeResource() {
		return computeResource;
	}

	public void setComputeResource(final ResourceHandle computeResource) {
		this.computeResource = computeResource;
	}

	public AffectedVnfc metadata(final Map<String, String> metadata) {
		this.metadata = metadata;
		return this;
	}

	/**
	 * Metadata about this resource. The content of this attribute shall be a copy
	 * of the content of the \&quot;metadata\&quot; attribute of the
	 * VnfcResourceInfo structure.
	 *
	 * @return metadata
	 **/
	@JsonProperty("metadata")
	@Schema(description = "Metadata about this resource. The content of this attribute shall be a copy of the content of the \"metadata\" attribute of the VnfcResourceInfo structure. ")
	public Map<String, String> getMetadata() {
		return metadata;
	}

	public void setMetadata(final Map<String, String> metadata) {
		this.metadata = metadata;
	}

	public AffectedVnfc affectedVnfcCpIds(final List<String> affectedVnfcCpIds) {
		this.affectedVnfcCpIds = affectedVnfcCpIds;
		return this;
	}

	public AffectedVnfc addAffectedVnfcCpIdsItem(final String affectedVnfcCpIdsItem) {
		if (this.affectedVnfcCpIds == null) {
			this.affectedVnfcCpIds = new ArrayList<>();
		}
		this.affectedVnfcCpIds.add(affectedVnfcCpIdsItem);
		return this;
	}

	/**
	 * Identifiers of CP(s) of the VNFC instance that were affected by the change.
	 * Shall be present for those affected CPs of the VNFC instance that are
	 * associated to an external CP of the VNF instance. May be present for further
	 * affected CPs of the VNFC instance.
	 *
	 * @return affectedVnfcCpIds
	 **/
	@JsonProperty("affectedVnfcCpIds")
	@Schema(description = "Identifiers of CP(s) of the VNFC instance that were affected by the change.  Shall be present for those affected CPs of the VNFC instance that are associated to an external CP of the VNF instance. May be present for further affected CPs of the VNFC instance. ")
	public List<String> getAffectedVnfcCpIds() {
		return affectedVnfcCpIds;
	}

	public void setAffectedVnfcCpIds(final List<String> affectedVnfcCpIds) {
		this.affectedVnfcCpIds = affectedVnfcCpIds;
	}

	public AffectedVnfc addedStorageResourceIds(final List<String> addedStorageResourceIds) {
		this.addedStorageResourceIds = addedStorageResourceIds;
		return this;
	}

	public AffectedVnfc addAddedStorageResourceIdsItem(final String addedStorageResourceIdsItem) {
		if (this.addedStorageResourceIds == null) {
			this.addedStorageResourceIds = new ArrayList<>();
		}
		this.addedStorageResourceIds.add(addedStorageResourceIdsItem);
		return this;
	}

	/**
	 * References to VirtualStorage resources that have been added. Each value
	 * refers to a VirtualStorageResourceInfo item in the VnfInstance that was added
	 * to the VNFC. It shall be provided if at least one storage resource was added
	 * to the VNFC.
	 *
	 * @return addedStorageResourceIds
	 **/
	@JsonProperty("addedStorageResourceIds")
	@Schema(description = "References to VirtualStorage resources that have been added. Each value refers to a VirtualStorageResourceInfo item in the VnfInstance that was added to the VNFC. It shall be provided if at least one storage resource was added to the VNFC. ")
	public List<String> getAddedStorageResourceIds() {
		return addedStorageResourceIds;
	}

	public void setAddedStorageResourceIds(final List<String> addedStorageResourceIds) {
		this.addedStorageResourceIds = addedStorageResourceIds;
	}

	public AffectedVnfc removedStorageResourceIds(final List<String> removedStorageResourceIds) {
		this.removedStorageResourceIds = removedStorageResourceIds;
		return this;
	}

	public AffectedVnfc addRemovedStorageResourceIdsItem(final String removedStorageResourceIdsItem) {
		if (this.removedStorageResourceIds == null) {
			this.removedStorageResourceIds = new ArrayList<>();
		}
		this.removedStorageResourceIds.add(removedStorageResourceIdsItem);
		return this;
	}

	/**
	 * References to VirtualStorage resources that have been removed. The value
	 * contains the identifier of a VirtualStorageResourceInfo item that has been
	 * removed from the VNFC, and might no longer exist in the VnfInstance. It shall
	 * be provided if at least one storage resource was removed from the VNFC.
	 *
	 * @return removedStorageResourceIds
	 **/
	@JsonProperty("removedStorageResourceIds")
	@Schema(description = "References to VirtualStorage resources that have been removed. The value contains the identifier of a VirtualStorageResourceInfo item that has been removed from the VNFC, and might no longer exist in the VnfInstance. It shall be provided if at least one storage resource was removed from the VNFC. ")
	public List<String> getRemovedStorageResourceIds() {
		return removedStorageResourceIds;
	}

	public void setRemovedStorageResourceIds(final List<String> removedStorageResourceIds) {
		this.removedStorageResourceIds = removedStorageResourceIds;
	}

	@Override
	public String toString() {
		final StringBuilder sb = new StringBuilder();
		sb.append("class AffectedVnfc {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    vduId: ").append(toIndentedString(vduId)).append("\n");
		sb.append("    changeType: ").append(toIndentedString(changeType)).append("\n");
		sb.append("    computeResource: ").append(toIndentedString(computeResource)).append("\n");
		sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
		sb.append("    affectedVnfcCpIds: ").append(toIndentedString(affectedVnfcCpIds)).append("\n");
		sb.append("    addedStorageResourceIds: ").append(toIndentedString(addedStorageResourceIds)).append("\n");
		sb.append("    removedStorageResourceIds: ").append(toIndentedString(removedStorageResourceIds)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(final java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
