#cloud-config
a10_blob: |
  hostname {{hostname}}
  ip dns primary {{primary_dns_ip}}
  ip dns secondary {{secondary_dns_ip}}
  interface management
    ip control-apps-use-mgmt-port
  glm use-mgmt-port
  glm token {{token}}
  glm enable-requests
  glm allocate-bandwidth 2
  glm send license-request
