<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metadata>
    <map>
        <entry>
            <key>FILE_TYPE</key>
            <value>text</value>
        </entry>
        <entry>
            <key>DATE_MODIFICATION</key>
            <value>1571845547171</value>
        </entry>
        <entry>
            <key>COMMENT</key>
            <value></value>
        </entry>
        <entry>
            <key>DATE_CREATION</key>
            <value>1561994093101</value>
        </entry>
        <entry>
            <key>TAG</key>
            <value></value>
        </entry>
        <entry>
            <key>TYPE</key>
            <value>UPLOAD</value>
        </entry>
    </map>
</metadata>
