<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metadata>
    <map>
        <entry>
            <key>FILE_TYPE</key>
            <value>text</value>
        </entry>
        <entry>
            <key>DATE_MODIFICATION</key>
            <value>1591808734954</value>
        </entry>
        <entry>
            <key>COMMENT</key>
            <value></value>
        </entry>
        <entry>
            <key>REPOSITORY</key>
            <value>CommandDefinition</value>
        </entry>
        <entry>
            <key>DATE_CREATION</key>
            <value>1591725083778</value>
        </entry>
        <entry>
            <key>CONFIGURATION_FILTER</key>
            <value></value>
        </entry>
        <entry>
            <key>TAG</key>
            <value>utility.php</value>
        </entry>
        <entry>
            <key>TYPE</key>
            <value>UPLOAD</value>
        </entry>
    </map>
</metadata>
