// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dns-api.proto

package com.ubiqube.etsi.mano.dns.api.v1;

public interface AddHostResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ubiqube.etsi.mano.dns.api.AddHostResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string hostName = 2;</code>
   * @return The hostName.
   */
  java.lang.String getHostName();
  /**
   * <code>string hostName = 2;</code>
   * @return The bytes for hostName.
   */
  com.google.protobuf.ByteString
      getHostNameBytes();

  /**
   * <code>int32 ttl = 3;</code>
   * @return The ttl.
   */
  int getTtl();

  /**
   * <code>string in = 4;</code>
   * @return The in.
   */
  java.lang.String getIn();
  /**
   * <code>string in = 4;</code>
   * @return The bytes for in.
   */
  com.google.protobuf.ByteString
      getInBytes();

  /**
   * <code>string recordType = 5;</code>
   * @return The recordType.
   */
  java.lang.String getRecordType();
  /**
   * <code>string recordType = 5;</code>
   * @return The bytes for recordType.
   */
  com.google.protobuf.ByteString
      getRecordTypeBytes();

  /**
   * <code>string value = 6;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 6;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
