// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dns-api.proto

package com.ubiqube.etsi.mano.dns.api.v1;

public final class DnsProto {
  private DnsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ubiqube_etsi_mano_dns_api_AddHostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ubiqube_etsi_mano_dns_api_AddHostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ubiqube_etsi_mano_dns_api_AddHostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ubiqube_etsi_mano_dns_api_AddHostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rdns-api.proto\022\035com.ubiqube.etsi.mano.d" +
      "ns.api\"2\n\016AddHostRequest\022\014\n\004name\030\001 \001(\t\022\022" +
      "\n\nrecordType\030\002 \001(\t\"k\n\017AddHostResponse\022\n\n" +
      "\002id\030\001 \001(\005\022\020\n\010hostName\030\002 \001(\t\022\013\n\003ttl\030\003 \001(\005" +
      "\022\n\n\002in\030\004 \001(\t\022\022\n\nrecordType\030\005 \001(\t\022\r\n\005valu" +
      "e\030\006 \001(\t\" \n\020ListHostsRequest\022\014\n\004zone\030\001 \001(" +
      "\t\"R\n\021ListHostsResponse\022=\n\005hosts\030\001 \003(\0132.." +
      "com.ubiqube.etsi.mano.dns.api.AddHostRes" +
      "ponse2\352\001\n\nDnsService\022j\n\007AddHost\022-.com.ub" +
      "iqube.etsi.mano.dns.api.AddHostRequest\032." +
      ".com.ubiqube.etsi.mano.dns.api.AddHostRe" +
      "sponse\"\000\022p\n\tListHosts\022/.com.ubiqube.etsi" +
      ".mano.dns.api.ListHostsRequest\0320.com.ubi" +
      "qube.etsi.mano.dns.api.ListHostsResponse" +
      "\"\000B.\n com.ubiqube.etsi.mano.dns.api.v1B\010" +
      "DnsProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ubiqube_etsi_mano_dns_api_AddHostRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ubiqube_etsi_mano_dns_api_AddHostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ubiqube_etsi_mano_dns_api_AddHostRequest_descriptor,
        new java.lang.String[] { "Name", "RecordType", });
    internal_static_com_ubiqube_etsi_mano_dns_api_AddHostResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ubiqube_etsi_mano_dns_api_AddHostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ubiqube_etsi_mano_dns_api_AddHostResponse_descriptor,
        new java.lang.String[] { "Id", "HostName", "Ttl", "In", "RecordType", "Value", });
    internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsRequest_descriptor,
        new java.lang.String[] { "Zone", });
    internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsResponse_descriptor,
        new java.lang.String[] { "Hosts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
