// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dns-api.proto

package com.ubiqube.etsi.mano.dns.api.v1;

/**
 * Protobuf type {@code com.ubiqube.etsi.mano.dns.api.ListHostsResponse}
 */
public  final class ListHostsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ubiqube.etsi.mano.dns.api.ListHostsResponse)
    ListHostsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListHostsResponse.newBuilder() to construct.
  private ListHostsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListHostsResponse() {
    hosts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListHostsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListHostsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              hosts_ = new java.util.ArrayList<com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            hosts_.add(
                input.readMessage(com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        hosts_ = java.util.Collections.unmodifiableList(hosts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ubiqube.etsi.mano.dns.api.v1.DnsProto.internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ubiqube.etsi.mano.dns.api.v1.DnsProto.internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse.class, com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse.Builder.class);
  }

  public static final int HOSTS_FIELD_NUMBER = 1;
  private java.util.List<com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse> hosts_;
  /**
   * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
   */
  public java.util.List<com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse> getHostsList() {
    return hosts_;
  }
  /**
   * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
   */
  public java.util.List<? extends com.ubiqube.etsi.mano.dns.api.v1.AddHostResponseOrBuilder> 
      getHostsOrBuilderList() {
    return hosts_;
  }
  /**
   * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
   */
  public int getHostsCount() {
    return hosts_.size();
  }
  /**
   * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
   */
  public com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse getHosts(int index) {
    return hosts_.get(index);
  }
  /**
   * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
   */
  public com.ubiqube.etsi.mano.dns.api.v1.AddHostResponseOrBuilder getHostsOrBuilder(
      int index) {
    return hosts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < hosts_.size(); i++) {
      output.writeMessage(1, hosts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < hosts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, hosts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse)) {
      return super.equals(obj);
    }
    com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse other = (com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse) obj;

    if (!getHostsList()
        .equals(other.getHostsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getHostsCount() > 0) {
      hash = (37 * hash) + HOSTS_FIELD_NUMBER;
      hash = (53 * hash) + getHostsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ubiqube.etsi.mano.dns.api.ListHostsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ubiqube.etsi.mano.dns.api.ListHostsResponse)
      com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ubiqube.etsi.mano.dns.api.v1.DnsProto.internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ubiqube.etsi.mano.dns.api.v1.DnsProto.internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse.class, com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse.Builder.class);
    }

    // Construct using com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHostsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (hostsBuilder_ == null) {
        hosts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        hostsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ubiqube.etsi.mano.dns.api.v1.DnsProto.internal_static_com_ubiqube_etsi_mano_dns_api_ListHostsResponse_descriptor;
    }

    @java.lang.Override
    public com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse getDefaultInstanceForType() {
      return com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse build() {
      com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse buildPartial() {
      com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse result = new com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse(this);
      int from_bitField0_ = bitField0_;
      if (hostsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          hosts_ = java.util.Collections.unmodifiableList(hosts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.hosts_ = hosts_;
      } else {
        result.hosts_ = hostsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse) {
        return mergeFrom((com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse other) {
      if (other == com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse.getDefaultInstance()) return this;
      if (hostsBuilder_ == null) {
        if (!other.hosts_.isEmpty()) {
          if (hosts_.isEmpty()) {
            hosts_ = other.hosts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHostsIsMutable();
            hosts_.addAll(other.hosts_);
          }
          onChanged();
        }
      } else {
        if (!other.hosts_.isEmpty()) {
          if (hostsBuilder_.isEmpty()) {
            hostsBuilder_.dispose();
            hostsBuilder_ = null;
            hosts_ = other.hosts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            hostsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHostsFieldBuilder() : null;
          } else {
            hostsBuilder_.addAllMessages(other.hosts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse> hosts_ =
      java.util.Collections.emptyList();
    private void ensureHostsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        hosts_ = new java.util.ArrayList<com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse>(hosts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse, com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.Builder, com.ubiqube.etsi.mano.dns.api.v1.AddHostResponseOrBuilder> hostsBuilder_;

    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public java.util.List<com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse> getHostsList() {
      if (hostsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(hosts_);
      } else {
        return hostsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public int getHostsCount() {
      if (hostsBuilder_ == null) {
        return hosts_.size();
      } else {
        return hostsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse getHosts(int index) {
      if (hostsBuilder_ == null) {
        return hosts_.get(index);
      } else {
        return hostsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public Builder setHosts(
        int index, com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse value) {
      if (hostsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHostsIsMutable();
        hosts_.set(index, value);
        onChanged();
      } else {
        hostsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public Builder setHosts(
        int index, com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.Builder builderForValue) {
      if (hostsBuilder_ == null) {
        ensureHostsIsMutable();
        hosts_.set(index, builderForValue.build());
        onChanged();
      } else {
        hostsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public Builder addHosts(com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse value) {
      if (hostsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHostsIsMutable();
        hosts_.add(value);
        onChanged();
      } else {
        hostsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public Builder addHosts(
        int index, com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse value) {
      if (hostsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHostsIsMutable();
        hosts_.add(index, value);
        onChanged();
      } else {
        hostsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public Builder addHosts(
        com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.Builder builderForValue) {
      if (hostsBuilder_ == null) {
        ensureHostsIsMutable();
        hosts_.add(builderForValue.build());
        onChanged();
      } else {
        hostsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public Builder addHosts(
        int index, com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.Builder builderForValue) {
      if (hostsBuilder_ == null) {
        ensureHostsIsMutable();
        hosts_.add(index, builderForValue.build());
        onChanged();
      } else {
        hostsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public Builder addAllHosts(
        java.lang.Iterable<? extends com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse> values) {
      if (hostsBuilder_ == null) {
        ensureHostsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hosts_);
        onChanged();
      } else {
        hostsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public Builder clearHosts() {
      if (hostsBuilder_ == null) {
        hosts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        hostsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public Builder removeHosts(int index) {
      if (hostsBuilder_ == null) {
        ensureHostsIsMutable();
        hosts_.remove(index);
        onChanged();
      } else {
        hostsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.Builder getHostsBuilder(
        int index) {
      return getHostsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public com.ubiqube.etsi.mano.dns.api.v1.AddHostResponseOrBuilder getHostsOrBuilder(
        int index) {
      if (hostsBuilder_ == null) {
        return hosts_.get(index);  } else {
        return hostsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public java.util.List<? extends com.ubiqube.etsi.mano.dns.api.v1.AddHostResponseOrBuilder> 
         getHostsOrBuilderList() {
      if (hostsBuilder_ != null) {
        return hostsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(hosts_);
      }
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.Builder addHostsBuilder() {
      return getHostsFieldBuilder().addBuilder(
          com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.Builder addHostsBuilder(
        int index) {
      return getHostsFieldBuilder().addBuilder(
          index, com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
     */
    public java.util.List<com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.Builder> 
         getHostsBuilderList() {
      return getHostsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse, com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.Builder, com.ubiqube.etsi.mano.dns.api.v1.AddHostResponseOrBuilder> 
        getHostsFieldBuilder() {
      if (hostsBuilder_ == null) {
        hostsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse, com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse.Builder, com.ubiqube.etsi.mano.dns.api.v1.AddHostResponseOrBuilder>(
                hosts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        hosts_ = null;
      }
      return hostsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ubiqube.etsi.mano.dns.api.ListHostsResponse)
  }

  // @@protoc_insertion_point(class_scope:com.ubiqube.etsi.mano.dns.api.ListHostsResponse)
  private static final com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse();
  }

  public static com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListHostsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListHostsResponse>() {
    @java.lang.Override
    public ListHostsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListHostsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListHostsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListHostsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ubiqube.etsi.mano.dns.api.v1.ListHostsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

