// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dns-api.proto

package com.ubiqube.etsi.mano.dns.api.v1;

public interface ListHostsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ubiqube.etsi.mano.dns.api.ListHostsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string zone = 1;</code>
   * @return The zone.
   */
  java.lang.String getZone();
  /**
   * <code>string zone = 1;</code>
   * @return The bytes for zone.
   */
  com.google.protobuf.ByteString
      getZoneBytes();
}
