package io.swagger.model;

import java.util.Objects;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The definition of the general \&quot;ProblemDetails\&quot; data structure from IETF RFC 7807 [19] is reproduced inthis structure. Compared to the general framework defined in IETF RFC 7807 [19], the \&quot;status\&quot; and \&quot;detail\&quot; attributes are mandated to be included by the present document, to ensure that the response contains additional textual information about an error. IETF RFC 7807 [19] foresees extensibility of the \&quot;ProblemDetails\&quot; type. It is possible that particular APIs in the present document, or particular implementations, define extensions to define additional attributes that provide more information about the error. The description column only provides some explanation of the meaning to Facilitate understanding of the design. For a full description, see IETF RFC 7807 [19].
 **/
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "The definition of the general \"ProblemDetails\" data structure from IETF RFC 7807 [19] is reproduced inthis structure. Compared to the general framework defined in IETF RFC 7807 [19], the \"status\" and \"detail\" attributes are mandated to be included by the present document, to ensure that the response contains additional textual information about an error. IETF RFC 7807 [19] foresees extensibility of the \"ProblemDetails\" type. It is possible that particular APIs in the present document, or particular implementations, define extensions to define additional attributes that provide more information about the error. The description column only provides some explanation of the meaning to Facilitate understanding of the design. For a full description, see IETF RFC 7807 [19]. ")

public class InlineResponse400 {

	private @Valid String type = null;
	private @Valid String title = null;
	private @Valid Integer status = null;
	private @Valid String detail = null;
	private @Valid String instance = null;

	/**
	 * A URI reference according to IETF RFC 3986 [5] that identifies the problem
	 * type. It is encouraged that the URI provides human-readable documentation for
	 * the problem (e.g. using HTML) when dereferenced. When this member is not
	 * present, its value is assumed to be \&quot;about:blank\&quot;.
	 **/
	public InlineResponse400 type(String type) {
		this.type = type;
		return this;
	}

	@ApiModelProperty(value = "A URI reference according to IETF RFC 3986 [5] that identifies the problem type. It is encouraged that the URI provides human-readable documentation for the problem (e.g. using HTML) when dereferenced. When this member is not present, its value is assumed to be \"about:blank\". ")
	@JsonProperty("type")
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/**
	 * A short, human-readable summary of the problem type. It should not change
	 * from occurrence to occurrence of the problem, except for purposes of
	 * localization. If type is given and other than \&quot;about:blank\&quot;, this
	 * attribute shall also be provided. A short, human-readable summary of the
	 * problem type. It SHOULD NOT change from occurrence to occurrence of the
	 * problem, except for purposes of localization (e.g., using proactive content
	 * negotiation; see [RFC7231], Section 3.4).
	 **/
	public InlineResponse400 title(String title) {
		this.title = title;
		return this;
	}

	@ApiModelProperty(value = "A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization. If type is given and other than \"about:blank\", this attribute shall also be provided. A short, human-readable summary of the problem type.  It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231], Section 3.4). ")
	@JsonProperty("title")
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * The HTTP status code for this occurrence of the problem. The HTTP status code
	 * ([RFC7231], Section 6) generated by the origin server for this occurrence of
	 * the problem.
	 **/
	public InlineResponse400 status(Integer status) {
		this.status = status;
		return this;
	}

	@ApiModelProperty(required = true, value = "The HTTP status code for this occurrence of the problem. The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem. ")
	@JsonProperty("status")
	@NotNull
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * A human-readable explanation specific to this occurrence of the problem.
	 **/
	public InlineResponse400 detail(String detail) {
		this.detail = detail;
		return this;
	}

	@ApiModelProperty(required = true, value = "A human-readable explanation specific to this occurrence of the problem. ")
	@JsonProperty("detail")
	@NotNull
	public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * A URI reference that identifies the specific occurrence of the problem. It
	 * may yield further information if dereferenced.
	 **/
	public InlineResponse400 instance(String instance) {
		this.instance = instance;
		return this;
	}

	@ApiModelProperty(value = "A URI reference that identifies the specific occurrence of the problem. It may yield further information if dereferenced. ")
	@JsonProperty("instance")
	public String getInstance() {
		return instance;
	}

	public void setInstance(String instance) {
		this.instance = instance;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (getClass() != o.getClass())) {
			return false;
		}
		final InlineResponse400 inlineResponse400 = (InlineResponse400) o;
		return Objects.equals(type, inlineResponse400.type) &&
				Objects.equals(title, inlineResponse400.title) &&
				Objects.equals(status, inlineResponse400.status) &&
				Objects.equals(detail, inlineResponse400.detail) &&
				Objects.equals(instance, inlineResponse400.instance);
	}

	@Override
	public int hashCode() {
		return Objects.hash(type, title, status, detail, instance);
	}

	@Override
	public String toString() {
		final StringBuilder sb = new StringBuilder();
		sb.append("class InlineResponse400 {\n");

		sb.append("    type: ").append(toIndentedString(type)).append("\n");
		sb.append("    title: ").append(toIndentedString(title)).append("\n");
		sb.append("    status: ").append(toIndentedString(status)).append("\n");
		sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
		sb.append("    instance: ").append(toIndentedString(instance)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
